### ISSUE TITLE
Write Unit test for UserAuthenticationImpl.java

### ISSUE THREAD

**Issue by kartik-tiwari** [kartik-tiwari/Chat-App#6]
https://github.com/kartik-tiwari/Chat-App/blob/master/src/main/java/chatapp/component/UserAuthenticationImpl.java

**Comment by durgeshwari** [comment]
i want to work on this

**Comment by kartik-tiwari** [comment]
closed with https://github.com/kartik-tiwari/Chat-App/pull/16
