### ISSUE TITLE
Write unit test for DeleteUser

### ISSUE THREAD

**Issue by kartik-tiwari** [kartik-tiwari/Chat-App#9]
https://github.com/kartik-tiwari/Chat-App/blob/master/src/main/java/chatapp/controller/DeleteUser.java

**Comment by imstillworthy** [comment]
Hi Kartik, please assign this issue to me, I wanna work on this. Thank you

**Comment by durgeshwari** [comment]
https://github.com/kartik-tiwari/Chat-App/pull/31
